[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer", "译文：Yobrave"]
description = "Rust 异步编程非官方中文."
language = "zh-CN"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.links]
# renderers = ["html"]

[output.html]
git_repository_url = "https://github.com/chinanf-boy/async-book-zh"
git_repository_icon = "fa-github"
site-url = "/async-book-zh/"

